### ISSUE TITLE
Broken on Rails 4.2.6 

### ISSUE THREAD

**Issue by jqr** [DocRaptor/docraptor-ruby#6]
On Rails 4.2.6 (latest is 4.2.7), a `NoMethodError` is caused when receiving data after document creation. It looks to be related to https://github.com/rails/rails/pull/25397 which is fixed in 4.2.7 and 5.0.0.

```
NoMethodError: undefined method `[]' for nil:NilClass
from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/logger_silence.rb:23:in `level'
from /app/vendor/bundle/ruby/2.2.0/gems/ethon-0.9.0/lib/ethon/easy/operations.rb:30:in `perform'
from /app/vendor/bundle/ruby/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/operations.rb:16:in `run'
from /app/vendor/bundle/ruby/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/cacheable.rb:18:in `run'
from /app/vendor/bundle/ruby/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/block_connection.rb:31:in `run'
from /app/vendor/bundle/ruby/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/stubbable.rb:25:in `run'
from /app/vendor/bundle/ruby/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/before.rb:26:in `run'
from /app/vendor/bundle/ruby/2.2.0/gems/docraptor-0.3.0/lib/docraptor/api_client.rb:37:in `call_api'
from /app/vendor/bundle/ruby/2.2.0/gems/docraptor-0.3.0/lib/docraptor/api/doc_api.rb:118:in `create_doc_with_http_info'
from /app/vendor/bundle/ruby/2.2.0/gems/docraptor-0.3.0/lib/docraptor/api/doc_api.rb:77:in `create_doc'
from (irb):7
from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
from /app/bin/rails:8:in `require’
```

**Comment by janxious** [comment]
This is fixed by upgrading Rails to a new minor versions, won't fix.
